### ISSUE TITLE
Pre-rehearsal checklist

### ISSUE THREAD

**Issue by delucis** [delucis/world-facer#21]
- [x] Finalise section 4 of score
- [x] Make video for section 5
- [x] Extend `news-maker` cues to full duration
- [x] Export video from FCP
- [x] Align audio with new video
- [x] Render video + audio from Reaper
- [x] Make slide with news reader address

## Monday

- [x] buy batteries for projector remote
- [X] print scores

### in hall

- [x] set up percussion (plastic, polystyrene, plate, 2 contact mics, brushes)
- [x] turn on projector
- [x] install QLab license
- [x] Add new video to QLab
- [x] Add slide with news reader address
- [x] Set-up laptop & run `news-server`
